//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJAX_SHOWTABLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyUnit
    {
        public int EmpID { get; set; }
        public string JobTitle { get; set; }
        public string UnitID { get; set; }
        public string UnitName { get; set; }
        public int Seniority { get; set; }
    }
}
